name = "hono-test"
main = "src/api/server.ts"
compatibility_date = "2025-10-15"
compatibility_flags = ["nodejs_compat", "enable_nodejs_http_modules", "enable_nodejs_http_server_modules"]
assets = { directory = "dist/client", binding = "ASSETS", serve_directly = false }
observability = { enabled = true }
port = 3005